# Generated by Django 5.0.1 on 2024-02-08 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_enterproduct_quantity_enter_notation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
