# Generated by Django 5.0.1 on 2024-02-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_enterproduct_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AlterField(
            model_name='enterproduct',
            name='quantity_enter_notation',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Ayrish'), (1, 'Qo`shish')], null=True),
        ),
    ]
